### ISSUE TITLE
Ricerca meteo per il giorno dell'evento

### ISSUE THREAD

**Issue by VeronicaChierzi** [VeronicaChierzi/BOTanici-SE2-Public#21]
Sono un utente e voglio vedere che tempo ci sarà il giorno dell'evento a cui voglio andare, posso cliccare su un pulsante oppure chiederlo

**Comment by Marco95conti** [comment]
HTD: Una volta trovato l'evento che mi interessa, devo poter vedere il meteo inerente all'evento in questione; per poter compiere la richiesta al servizio meteo necessito sia della data, sia del luogo dell'evento .
