### ISSUE TITLE
Creazione Database

### ISSUE THREAD

**Issue by ddlucad96** [VeronicaChierzi/BOTanici-SE2-Public#25]
Creazione database per gestire i dati provenienti dai vari webservices che l'applicazione utilizza.

**Comment by Marco95conti** [comment]
HTD: Una volta ricavati gli eventi dalle varie fonti (es. Facebook, Crushsite.it) i dati vengono conservati nel database per evitare continue richieste ai siti sorgente; periodicamente le informazioni vengono aggiornate con un tempo plausibile (es. 5-10 min).
