### ISSUE TITLE
Sistemare node_modules

### ISSUE THREAD

**Issue by VeronicaChierzi** [VeronicaChierzi/BOTanici-SE2-Public#28]
PROBLEMA con node_modules: conflitti perchè vengono installati in locale

**Comment by Marco95conti** [comment]
HTD:Installare i moduli in locale ed aggiungere la cartella node_module e il file package.json al file .gitignore, in modo tale che non vengano caricati ad ogni commit, infine aggiungere i moduli da installare alla lista nel file della cartella condivisa di Drive.
